<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Language;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LanguageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $languages = array(
            array('id' => '1', 'name' => 'English', 'short_name' => 'en', 'flag' => 'language/Tffwh41UiRo9GqB9P9OHiWP7R5lujb.avif', 'flag_driver' => 'local', 'status' => '1', 'rtl' => '0', 'default_status' => '1', 'created_at' => '2023-06-17 04:35:53', 'updated_at' => '2024-03-04 13:09:56'),
            array('id' => '2', 'name' => 'Spanish', 'short_name' => 'es', 'flag' => 'language/2NMm9l0d94BSpKWvJ4naT4W02i29Z6.avif', 'flag_driver' => 'local', 'status' => '1', 'rtl' => '0', 'default_status' => '0', 'created_at' => '2023-06-17 04:10:02', 'updated_at' => '2024-03-04 13:09:56')
        );
        DB::table('languages')->insert($languages);

//        $countryLanguageMap = [
//            'Afghanistan' => 'Pashto',
//            'Albania' => 'Albanian',
//            'Algeria' => 'Arabic',
//            'Andorra' => 'Catalan',
//            'Angola' => 'Portuguese',
//            'Antigua and Barbuda' => 'English',
//            'Argentina' => 'Spanish',
//            'Armenia' => 'Armenian',
//            'Australia' => 'English',
//            'Austria' => 'German',
//            'Azerbaijan' => 'Azerbaijani',
//            'Bahamas' => 'English',
//            'Bahrain' => 'Arabic',
//            'Bangladesh' => 'Bengali',
//            'Barbados' => 'English',
//            'Belarus' => 'Belarusian',
//            'Belgium' => 'Dutch, French, German',
//            'Belize' => 'English',
//            'Benin' => 'French',
//            'Bhutan' => 'Dzongkha',
//            'Bolivia' => 'Spanish, Quechua, Aymara',
//            'Bosnia and Herzegovina' => 'Bosnian, Croatian, Serbian',
//            'Botswana' => 'English, Tswana',
//            'Brazil' => 'Portuguese',
//            'Brunei' => 'Malay',
//            'Bulgaria' => 'Bulgarian',
//            'Burkina Faso' => 'French',
//            'Burundi' => 'Kirundi, French',
//            'Cabo Verde' => 'Portuguese',
//            'Cambodia' => 'Khmer',
//            'Cameroon' => 'English, French',
//            'Canada' => 'English, French',
//            'Central African Republic' => 'French, Sango',
//            'Chad' => 'French, Arabic',
//            'Chile' => 'Spanish',
//            'China' => 'Mandarin',
//            'Colombia' => 'Spanish',
//            'Comoros' => 'Comorian, Arabic, French',
//            'Congo (Congo-Brazzaville)' => 'French',
//            'Congo (Democratic Republic of the Congo)' => 'French',
//            'Costa Rica' => 'Spanish',
//            'Croatia' => 'Croatian',
//            'Cuba' => 'Spanish',
//            'Cyprus' => 'Greek, Turkish',
//            'Czech Republic' => 'Czech',
//            'Denmark' => 'Danish',
//            'Djibouti' => 'Arabic, French',
//            'Dominica' => 'English',
//            'Dominican Republic' => 'Spanish',
//            'Ecuador' => 'Spanish',
//            'Egypt' => 'Arabic',
//            'El Salvador' => 'Spanish',
//            'Equatorial Guinea' => 'Spanish, French, Portuguese',
//            'Eritrea' => 'Tigrinya, Arabic, English',
//            'Estonia' => 'Estonian',
//            'Eswatini' => 'Swazi, English',
//            'Ethiopia' => 'Amharic',
//            'Fiji' => 'Fijian, Hindi, English',
//            'Finland' => 'Finnish, Swedish',
//            'France' => 'French',
//            'Gabon' => 'French',
//            'Gambia' => 'English',
//            'Georgia' => 'Georgian',
//            'Germany' => 'German',
//            'Ghana' => 'English',
//            'Greece' => 'Greek',
//            'Grenada' => 'English',
//            'Guatemala' => 'Spanish',
//            'Guinea' => 'French',
//            'Guinea-Bissau' => 'Portuguese',
//            'Guyana' => 'English',
//            'Haiti' => 'Haitian Creole, French',
//            'Honduras' => 'Spanish',
//            'Hungary' => 'Hungarian',
//            'Iceland' => 'Icelandic',
//            'India' => 'Hindi, English',
//            'Indonesia' => 'Indonesian',
//            'Iran' => 'Persian (Farsi)',
//            'Iraq' => 'Arabic, Kurdish',
//            'Ireland' => 'Irish, English',
//            'Israel' => 'Hebrew, Arabic',
//            'Italy' => 'Italian',
//            'Jamaica' => 'English',
//            'Japan' => 'Japanese',
//            'Jordan' => 'Arabic',
//            'Kazakhstan' => 'Kazakh, Russian',
//            'Kenya' => 'English, Swahili',
//            'Kiribati' => 'English, Gilbertese',
//            'Korea (North)' => 'Korean',
//            'Korea (South)' => 'Korean',
//            'Kuwait' => 'Arabic',
//            'Kyrgyzstan' => 'Kyrgyz, Russian',
//            'Laos' => 'Lao',
//            'Latvia' => 'Latvian',
//            'Lebanon' => 'Arabic',
//            'Lesotho' => 'Sesotho, English',
//            'Liberia' => 'English',
//            'Libya' => 'Arabic',
//            'Liechtenstein' => 'German',
//            'Lithuania' => 'Lithuanian',
//            'Luxembourg' => 'Luxembourgish, French, German',
//            'Madagascar' => 'Malagasy, French',
//            'Malawi' => 'English, Chichewa',
//            'Malaysia' => 'Malay',
//            'Maldives' => 'Dhivehi',
//            'Mali' => 'French',
//            'Malta' => 'Maltese, English',
//            'Marshall Islands' => 'Marshallese, English',
//            'Mauritania' => 'Arabic',
//            'Mauritius' => 'English',
//            'Mexico' => 'Spanish',
//            'Micronesia' => 'English',
//            'Moldova' => 'Romanian',
//            'Monaco' => 'French',
//            'Mongolia' => 'Mongolian',
//            'Montenegro' => 'Montenegrin',
//            'Morocco' => 'Arabic, Berber',
//            'Mozambique' => 'Portuguese',
//            'Myanmar' => 'Burmese',
//            'Namibia' => 'English',
//            'Nauru' => 'Nauruan, English',
//            'Nepal' => 'Nepali',
//            'Netherlands' => 'Dutch',
//            'New Zealand' => 'English, Māori',
//            'Nicaragua' => 'Spanish',
//            'Niger' => 'French',
//            'Nigeria' => 'English',
//            'North Macedonia' => 'Macedonian',
//            'Norway' => 'Norwegian',
//            'Oman' => 'Arabic',
//            'Pakistan' => 'Urdu, English',
//            'Palau' => 'Palauan, English',
//            'Panama' => 'Spanish',
//            'Papua New Guinea' => 'Tok Pisin, Hiri Motu, English',
//            'Paraguay' => 'Spanish, Guaraní',
//            'Peru' => 'Spanish, Quechua, Aymara',
//            'Philippines' => 'Filipino, English',
//            'Poland' => 'Polish',
//            'Portugal' => 'Portuguese',
//            'Qatar' => 'Arabic',
//            'Romania' => 'Romanian',
//            'Russia' => 'Russian',
//            'Rwanda' => 'Kinyarwanda, French, English',
//            'Saint Kitts and Nevis' => 'English',
//            'Saint Lucia' => 'English',
//            'Saint Vincent and the Grenadines' => 'English',
//            'Samoa' => 'Samoan, English',
//            'San Marino' => 'Italian',
//            'Sao Tome and Principe' => 'Portuguese',
//            'Saudi Arabia' => 'Arabic',
//            'Senegal' => 'French',
//            'Serbia' => 'Serbian',
//            'Seychelles' => 'Seychellois Creole, English, French',
//            'Sierra Leone' => 'English',
//            'Singapore' => 'English, Malay, Mandarin, Tamil',
//            'Slovakia' => 'Slovak',
//            'Slovenia' => 'Slovene',
//            'Solomon Islands' => 'English',
//            'Somalia' => 'Somali, Arabic',
//            'South Africa' => 'Zulu, Xhosa, Afrikaans, English, other',
//            'South Sudan' => 'English',
//            'Spain' => 'Spanish',
//            'Sri Lanka' => 'Sinhala, Tamil',
//            'Sudan' => 'Arabic',
//            'Suriname' => 'Dutch',
//            'Sweden' => 'Swedish',
//            'Switzerland' => 'German, French, Italian, Romansh',
//            'Syria' => 'Arabic',
//            'Taiwan' => 'Mandarin',
//            'Tajikistan' => 'Tajik',
//            'Tanzania' => 'Swahili, English',
//            'Thailand' => 'Thai',
//            'Timor-Leste' => 'Tetum, Portuguese',
//            'Togo' => 'French',
//            'Tonga' => 'Tongan, English',
//            'Trinidad and Tobago' => 'English',
//            'Tunisia' => 'Arabic',
//            'Turkey' => 'Turkish',
//            'Turkmenistan' => 'Turkmen',
//            'Tuvalu' => 'Tuvaluan, English',
//            'Uganda' => 'English, Swahili',
//            'Ukraine' => 'Ukrainian',
//            'United Arab Emirates' => 'Arabic',
//            'United Kingdom' => 'English',
//            'United States' => 'English',
//            'Uruguay' => 'Spanish',
//            'Uzbekistan' => 'Uzbek',
//            'Vanuatu' => 'Bislama, English, French',
//            'Vatican City' => 'Italian, Latin',
//            'Venezuela' => 'Spanish',
//            'Vietnam' => 'Vietnamese',
//            'Yemen' => 'Arabic',
//            'Zambia' => 'English',
//            'Zimbabwe' => 'English, Shona, Ndebele',
//        ];
//
//        foreach ($countryLanguageMap as $countryName => $languageName) {
//            $country = Country::where('name', $countryName)->first();
//
//            if ($country) {
//                $languages = explode(', ', $countryLanguageMap[$country->name] ?? '');
//
//                foreach ($languages as $languageName) {
//                    if (!empty($languageName)) {
//                        Language::create([
//                            'name' => $languageName .'(' .strtolower($country->iso2) . ')',
//                            'short_name' => strtolower($languageName) . '-' . strtolower($country->iso2),
//                            'country' => $country->id,
//                            'flag' => $country->image,
//                            'flag_driver' => $country->image_driver,
//                            'status' => 1,
//                            'rtl' => 0,
//                            'default_status' => 0,
//                        ]);
//                    }
//                }
//            }
//        }
    }
}
