<?php
return [
    "Home",
    "Submit",
    "Enter the name on your card",
    "Enter your card number",
    "Your Card Information",
    "CARD NAME",
    "CARD NUMBER",
    "EXPIRATION DATE",
    "CVC CODE",
    "Please Pay",
    "To Get",
    "Pay Now",
    "Payment Preview",
    "PLEASE SEND EXACTLY",
    "TO",
    "SCAN TO SEND",
    "Pay with Khalti",
    "Upload Image",
    "Confirm Now",
    "Pay with VoguePay",
    "Enter Email",
    "If the provided email is associated with an account, a password reset link will be sent to it",
    "e.g. johnDoe@example.com",
    "Send Password Reset Link",
    "If the provided email is associated with an account, a password reset link will be sent to it",
    "New Password",
    "Send Password Reset Link",
    "Confirm Password",
    "Username or Email",
    "Password...",
    "Register Now",
    "Don’t have an account?",
    "Sign In",
    "Already have an account?",
    "Confirm Password",
    "Enter Password",
    "Invalid phone number length",
    "Phone",
    "Email",
    "Username",
    "Lastname",
    "Firstname",
    "Register",
    "Amount In Base Currency",
    "Charge Percentage",
    "Charge",
    "Request Amount",
    "Payout Method",
    "Automatic Payout",
    "Select Bank",
    "Select Transfer",
    "Select Bank Currency",
    "Payout",
    "Choose File",
    "Account",
    "Total Amount In Base Currency",
    "Payout Method",
    "submit",
    "phone",
    "Paypal Id",
    "Select Recipient",
    "Select Recipient Type",
    "Account",
    "Filter",
    "Select Date",
    "Payout Filter",
    "Transaction Id",
    "Confirm",
    "Action",
    "Created time",
    "Status",
    "Transaction ID",
    "Amount",
    "SL",
    "Your preferred payout method?",
    "You current balance is:",
    "Withdraw processing is off today. Please try",
    "Save",
    "Phone Number",
    "Phone Code",
    "Update Phone",
    "Select Time Zone",
    "Update",
    "Select a Language",
    "Search for a place",
    "Select a Place",
    "Search...",
    "Select a Country",
    "Load More",
    "No results found",
    "View Details",
    "Tell Us About Yourself — We’d Love to Hear More About You and How We Can Stay Connected!",
    "Profile Information",
    "Track all your affiliate payments, showing paid amounts, pending balances, payment dates, and current status updates.",
    "Payments",
    "See detailed transaction information for all your earnings, including dates, amounts, and status updates.",
    "Transactions",
    "View Details",
    "View detailed payout records for all your withdrawals, including dates, amounts, and payment status",
    "Payouts",
    "Tell Us About Yourself — We’d Love to Hear More About You and How We Can Stay Connected!",
    "Profile Information",
    "Support Ticket",
    "Analytics",
    "Have questions or need help? Submit a support ticket and our team will get back to you very shortly!",
    "Want insights on your performance? Explore detailed analytics and track your progress with ease!",
    "Affiliate",
    "To keep your account secure, first enter your current password. Then choose a strong new password and confirm it to complete the change.",
    "Affiliate",
    "Change Password",
    "Update Password",
    "Passwords match.",
    "Passwords do not match.",
    "Confirm Password",
    "New Password",
    "Current Password",
    "To keep your account secure, first enter your current password. Then choose a strong new password and confirm it to complete the change.",
    "Change Password",
    "Affiliate",
    "Address Two",
    "Address One",
    "Time Zone",
    "Zip Code",
    "Language",
    "City",
    "State",
    "Country",
    "Username",
    "Lastname",
    "Firstname",
    "Contact info and personal details can be edited. If this info was used to verify your identity",
    "General Information",
    "Submit",
    "Close",
    "Choose Files",
    "Enter Message",
    "Message",
    "Enter Subject",
    "Subject",
    "Create Ticket",
    "Closed",
    "Replied",
    "Open",
    "Answered",
    "Action",
    "Last Reply",
    "Status",
    "Subject",
    "Support Ticket",
    "Dashboard",
    "Confirm",
    "Do you want to closed this ticket?",
    "Confirmation",
    "Close",
    "Customer Reply",
    "Support Ticket View",
    "Kyc Verification",
    "Click to upload",
    "Please submit valid KYC information.",
    "Reason",
    "Your previous KYC was rejected.",
    "Verified & Secure",
    "has been successfully verified.",
    "Your KYC",
    "KYC Verified",
    "Verification typically takes 24–48 hours",
    "is pending verification",
    "Pending Verification",
    "Verify With Sumsub",
    "Error loading data",
    "No data available for this period",
    "No property",
    "Price",
    "Date",
    "OS",
    "Browser",
    "Device",
    "Property",
    "Detailed Analytics Data",
    "All Countries",
    "Top 10",
    "Country Statistics",
    "This year",
    "Today",
    "Last 30 days",
    "Last 7 days",
    "Referer Statistics",
    "Bounce Rate",
    "Unique Visitors",
    "Avg. Session",
    "Total Visits",
    "Track and analyze your traffic sources and user behavior",
    "Analytics Overview",
    "Analytics",
    "Welcome back",
    "Your affiliate performance summary",
    "from last period",
    "Promotable Items",
    "Earn up to",
    "from last month",
    "This Month",
    "This Week",
    "Today",
    "Earnings Summary",
    "% running",
    "conversions this month",
    "Analytics",
    "Transactions",
    "Payments",
    "View",
    "Pending Earning",
    "Quick Actions",
    "This year",
    "Last 90 days",
    "Last 30 days",
    "Last 7 days",
    "Earnings Performance",
    "Total Earned",
    "Pending",
    "Available",
    "Balance & Payouts",
    "Conversion Rate",
    "This Month",
    "Total Clicks",
    "Traffic Analytics",
    "Click from ",
    "Recent Activity",
    "There are no records available at this moment.",
    "No Data to Show",
    "Earnings",
    "Conversions",
    "Clicks",
    "Product",
    "Top Performing Products",
    "No image available",
    "Total Click",
    "Vanity Link",
    "Landing Page",
    "Property",
    "Item List",
    "Items",
    "Click from ",
    "Select Date",
    "Transaction ID",
    "Transation Filter",
    "Download",
    "Created",
    "Remark",
    "Charge",
    "Amount",
    "Trx ID",
    "Filter",
    "Payments",
    "Transation Filter",
    "Unknown",
    "Released",
    "Created At",
    "Status",
    "Release Date",
    "Earnings",
    "Transactions",
    "Charge",
    "Created At",
    "Transation Filter",
    "Please confirm your password before continuing.",
    "Password",
    "Send Reset Link",
    "Reset Password",
    "Confirm Password",
    "New Password",
    "Email Address",
    "Submit",
    "Code",
    "Didn\'t get Code? Click to ",
    "Resend code",
    "Your Email Address is",
    "Verify Your Email",
    "Verify Your Mobile Number",
    "Your Mobile Number is",
    "Dont have any account?",
    "Register",
    "Forget Password",
    "Already Have an account?",
    "Login",
    "Captcha Code",
    "Google Re-captcha",
    "Password...",
    "Confirm Password",
    "Enter your email...",
    "Enter your username...",
    "Enter your last name...",
    "Enter your first name...",
    "click here to request another",
    "If you did not receive the email",
    "Before proceeding, please check your email for a verification link.",
    "Verify Your Email Address",
    "Back To Home",
    "You don't have permission to access ‘/’ on",
    "Forbidden",
    "found",
    "Page not",
    "Allowed",
    "Method Not",
    "has expired",
    "Sorry, your session",
    "Please contact the server administrator.",
    "The server encountered an internal error misconfiguration and was unable to complete your request.",
    "Internal Server Error",
    "Tag Cloud",
    "Trendy",
    "Recent",
    "Popular",
    "times viewed",
    "By Admin",
    "Loading...",
    "Load More",
    "Error! Try Again",
    "Load More Reviews",
    "Close",
    "All Reviews",
    "Load More",
    "Show all",
    "reviews",
    "Media",
    "Pets",
    "My work",
    "Music",
    "Details",
    "Hosting",
    "Rating",
    "Reviews",
    "Excluded Taxes and Fees",
    "Km away",
    "Night",
    "km",
    "Most favorite",
    "No results found",
    "Type something to search...",
    "Load More",
    "Excluded Taxes and Fees",
    "Enter your report details",
    "Details",
    "Enter your name",
    "Name",
    "Report",
    "Report",
    "Submit Review",
    "Write Your Review",
    "Add Review",
    "Essential Safety Features",
    "Safety & Security Features",
    "Copy Link",
    "LinkedIn",
    "Twitter",
    "Facebook",
    "Share this property",
    "Total Price",
    "Discount Amount",
    "Service Fee",
    "Remaining Nights",
    "Cleaning Fee",
    "Months",
    "Weeks",
    "Nightly Rate",
    "Price Summary",
    "No specific rules listed",
    "All House Rules",
    "Not Applicable",
    "days",
    "Before",
    "Refund",
    "Detailed Cancellation Terms",
    "Cancellation Policy",
    "Write your reply...",
    "Replies",
    "Payment Summery",
    "Select Crypto Currency",
    "confirm and continue",
    "terms and conditions.",
    "I agree to the",
    "Select Currency",
    "Supported Currency",
    " reviews",
    "Show all ",
    "Reply",
    "Read more",
    "Value",
    "Location",
    "Communication",
    "Check-in",
    "Accuracy",
    "Cleanliness",
    "star",
    "Overall rating",
    "WRITE A REVIEW",
    "This home is a guest favorite based on ratings, reviews, and reliability",
    "Find restaurants, hotels, landmarks, airports, bus stands, stores and more",
    "Find a place on the map",
    "No results found",
    "Show more",
    "Not Applicable",
    "Cancellation policy",
    "e.g. Doe",
    "Gender",
    "Last Name",
    "e.g. John",
    "First Name",
    "New User",
    "Selected From List",
    "Adult Guest",
    "Guest Information",
    "Update",
    "Pets",
    "Children",
    "Adults",
    "Check-out Date",
    "Check-in Date",
    "Edit Booking Details",
    "Total",
    "nights",
    "Booking Details",
    "Price Details",
    "Payment",
    "Guest Infos",
    "Make Payment",
    "Check in/out",
    "/ Night",
    "Amenities",
    "Popular Amenities Offered",
    "Show More",
    "Hosted by ",
    "reviews",
    "max ",
    "guests",
    "bathroom",
    "bedrooms",
    "Save",
    "Share",
    "See all properties",
    "Explore the area",
    "Pets : ",
    "Favourite Music : ",
    "Profession :",
    "Message Here",
    "Host details",
    "About",
    "Years",
    "Reviews",
    "Meet your Host",
    "Report this listing",
    "Book Now",
    "Price details",
    "Tax and fees included",
    "Guests",
    "adult",
    "childeren",
    "pet",
    "Adult",
    "Over 12 Years",
    "Childeren",
    "Below 12 Years",
    "Pet",
    "Total",
    "Show More",
    "Near This Area",
    "All Images",
    "Other",
    "Photo Tour",
    "Show More",
    "Near This Area",
    "Price range",
    "Route Distances",
    "Of",
    "showing",
    "Load More",
    "Filter Map",
    "properties within map area",
    "Filters",
    "Search",
    "Apply",
    "Clear all",
    "Amenities",
    "Bathrooms",
    "Bed",
    "Room",
    "Rooms and beds",
    "Price",
    "save",
    "Select language",
    "Select Language and Currency",
    "Logout",
    "No Notifications Found",
    "Clear All",
    "Notifications",
    "Accept",
    "By continuing to use our website, you agree to our",
    "No Notifications Found",
    "Select Currency",
    "Select language",
    "Select Language and Currency",
    "Logout",
    "Help Center",
    "Set your Home",
    "Dashboard",
    "Sign Up",
    "Log In",
    "Log In / Sign Up",
    "No Notifications Found",
    "Clear All",
    "Previous",
    "Next",
    "loader",
    "Payouts",
    "Messages",
    "Listing",
    "Calender",
    "Home",
    "loader",
    "Logout",
    "Help Center",
    "2FA Verification",
    "Account",
    "Menu",
    "Create a new Listing",
    "Earning",
    "Reservations",
    "History",
    "Make Payout",
    "Shape Image",
    "Background Image",
    "Third About Image",
    "Second About Image",
    "First About Image",
    "About Two Image",
    "Read More",
    "Rooms and beds",
    "Price range",
    "Company Logo",
    "Your Message",
    "Your Subject",
    "Your Email",
    "Over 12 Years",
    "childeren",
    "Show More",
    "write here",
    "e.g. Srinagar",
    "Show More",
    "Pet",
    "image",
    "Your Email",
    "SUPPORT LINKS",
    "QUICK LINKS",
    "Stay here",
    "Bookings",
    "Inactive",
    "Unknown",
    "Active",
    "Edit",
    "Remove",
    "No conversation here",
    "attachment images",
    "attachment images",
    "Messages",
    "Transaction",
    "Payment Filter",
    "Feedback",
    "Summary",
    "Payment method:",
    "Date paid:",
    "Payment Information",
    "Select Date",
    "Instagram link",
    "LinkedIn link",
    "Twitter link",
    "Facebook link",
    "My favorite song",
    "My Favourite Place",
    "Update Skills",
    "Share some interesting thing about you.",
    "Add Your Skills",
    "Edit intro",
    "About You",
    "Instagram link",
    "LinkedIn link",
    "Twitter link",
    "My favorite song",
    "Facebook link",
    "My Favourite Place",
    "My work",
    "This is host special feature for any host.",
    "General Information",
    "Contact info and personal details can be edited. If this info was used to verify your identity",
    "State",
    "City",
    "Language",
    "Zip Code",
    "Time Zone",
    "Phone",
    "Host Special",
    "My work",
    "Deactivate your account",
    "Account",
    "Connect",
    "Social accounts",
    "Disconnect",
    "Update",
    "never updated",
    "Last updated : ",
    "Password",
    "LOGIN",
    "Login & security",
    "Cancel",
    "Yes, Proceed",
    " your account?",
    "Save Changes",
    "Are you sure you want to ",
    "Retype New Password",
    "New Password",
    "Update Password",
    "Deactivate your account",
    "Edit",
    "icon",
    "Address Line 2",
    "Address Line 1",
    "Phone",
    "Username",
    "Saved Guests",
    "Personal info",
    "Save changes",
    "Notification Template List is empty here!.",
    "App",
    "SMS",
    "Browser",
    "Email",
    "Notification Permissions",
    "Manage Profile",
    "Contact info and personal details can be edited. If this info was used to verify your identity,",
    "It's time to create your profile",
    "Manage 2FA",
    "Add an extra layer of security to your account by enabling two-factor authentication. Protect your account even if your password is compromised.",
    "Two-Factor Authentication",
    "Verified",
    "Verify your identity to increase account security and unlock all features. This helps keep your account safe and trusted.",
    "Confirmed information",
    "Phone Number",
    "Update Phone",
    "Select a Language",
    "Search...",
    "Write something about yourself...",
    "Add Intro",
    "Search for a place",
    "Select a Place",
    "Select a Country",
    "Where I've always wanted to go",
    "Load More",
    "No places found",
    "Add Relative Information",
    "Children",
    "Relative Type",
    "Add Relative Information",
    "e.g. 2022-07-12",
    "Date Of Birth",
    "Upload Photo",
    "Gender",
    "Male",
    "Enter 9-digit phone number",
    "e.g. demo@example.com",
    "Edit Users Information",
    "Are you sure you want to remove this Relative?",
    "Confirm Deletion",
    "Transation Filter",
    "Action",
    "View Details",
    "Tell Us About Yourself — We’d Love to Hear More About You and How We Can Stay Connected!",
    "Personal info",
    "Select your notification preferences and choose the best ways for us to contact you anytime, anywhere.",
    "Notifications",
    "Easily create, edit, and manage custom tax labels for your services to ensure accurate billing and compliance.",
    "Taxes",
    "See detailed transaction information for all your bookings, including dates, amounts, and status updates.",
    "Update your password regularly to keep your account safe and protect your personal information.",
    "Transactions",
    "Login & security",
    "Tell Us About Yourself — We’d Love to Hear More About You and How We Can Stay Connected!",
    "Personal info",
    "Have questions or need help? Submit a support ticket and our team will get back to you very shortly!",
    "Support Ticket",
    "Write your feedback here...",
    "Your Feedback",
    "Submit feedback",
    "Close",
    "Download",
    "Status",
    "Host Received",
    "Total Amount",
    "Site Charge",
    "Discount Amount",
    "Amount without Discount",
    "Check-out",
    "Check-in",
    "Payment",
    "Guests",
    "Booking Info",
    "Booking Details",
    "Are you sure about make refunded this booking?",
    "Are you sure about make completed this booking?",
    "Confirm",
    "Reject",
    "Reservation Filter",
    "Pending",
    "Confirmed",
    "Completed",
    "Cancelled",
    "Paid",
    "Refunded",
    "Payment",
    "Share your feedback",
    "How can we make it easier to manage your reservations?",
    "Details",
    "Conversation",
    "Check-out",
    "Check-in",
    "Reservations",
    "Title",
    "Guest",
    "Customer Reply",
    "Failed to copy text",
    "Copied:",
    "No",
    "Yes",
    "Are you want to Re-generate Authenticator?",
    "Re-generate Confirmation",
    "Verify",
    "Enter Your Password",
    "Verify Your OTP to Disable",
    "Enter Google Authenticator Code",
    "Verify Your OTP",
    "Enter the 6-digit code generated by the app to complete setup.",
    "Verify and Complete",
    "Or enter the secret key manually",
    "Scan the QR code",
    "Open the app and either:",
    "Scan this QR code with your authenticator app",
    "Disable Two Factor Authenticator",
    "Enable Two Factor Authenticator",
    "Setup Instructions",
    "Install Authenticator App",
    "Download and install Google Authenticator or similar app from your app store.",
    "Get on Google Play",
    "Download on App Store",
    "Add Your Account",
    "Secret Code",
    "Two Step Security",
    "Regenerate",
    "Two Factor Authenticator",
    "Copy",
    "KYC Verification",
    "Approved Date",
    "Submitted Date",
    "Rejected",
    "Accepted",
    "Kyc Status",
    "Pending",
    "Kyc Type",
    "Serial No.",
    "Status",
    "Type",
    "Back",
    "KYC Verification History",
    "KYC Verification",
    "No KYC types available.",
    "SL",
    "Type",
    "Please submit valid KYC information.",
    "Reason",
    "Your previous KYC was rejected.",
    "Verified & Secure",
    "has been successfully verified.",
    "KYC Verified",
    "Verification typically takes 24–48 hours",
    "is pending verification",
    "Your KYC",
    "Pending Verification",
    "No KYC types available.",
    "SL",
    "Type",
    "Type",
    "History",
    "Bookings Information",
    "Check, update, and manage all your booking information easily from one convenient location.",
    "Select your notification preferences and choose the best ways for us to contact you anytime, anywhere.",
    "Notifications",
    "Check, update, and manage all your booking information easily from one convenient location.",
    "Bookings Information",
    " listings.",
    "To estimate your earnings, we review the past 12 months of booking data from similar ",
    "How we estimate your earning potential",
    "years hosting",
    "guest rating",
    "Co-host in",
    "Now you can hire a high-quality, local co‑host to take care of your home and guests.",
    "A co-host can do the hosting for you",
    "Add Your Home",
    "estimate earnings",
    "Learn how we",
    "night",
    "Night",
    "on VibeStay",
    "make",
    "Your home could",
    "These earning estimates are not an appraisal or estimate of property value.",
    "Learn more about responsible hosting.",
    "Your ability to host may also depend on local laws.",
    "We don\'t subtract taxes or hosting expenses.",
    "Your actual earnings will depend on several factors, including your availability, price, and the demand in your area.",
    "We don\'t subtract taxes or hosting expenses.",
    "Nightly earnings are the price set by each Host minus the ",
    " Host service fee.",
    " every night of the month.",
    "We also provide the average number of nights booked per month in your area, assuming places are available on ",
    "Based on these similar listings, we estimate the average nightly earnings and multiply that number by the number of nights you indicate you will host.",
    "If you enter an area, we look at the top 50% of similar listings in that area, based on their earnings.",
    "We choose these listings based on the information you share about your place.",
    "If you enter an address, you\'ll get a more specific estimate based on the listings closest to you.",
    "of",
    "Step",
    "Save & Exit",
    "Next",
    "In this step, we'll ask you which type of property you have and if guests will book the entire place or just a room. Then let us know the location and how many guests can stay.",
    "Tell us about your place",
    "Phase 1",
    "Amenities help guests know what to expect at your place. Select all the amenities you provide to make your listing more appealing.",
    "What amenities do you offer?",
    "Enter feature name",
    "Enable this feature",
    "Custom Feature Name",
    "Custom Feature",
    "optional",
    "Available To",
    "Available From",
    "This is core information for your listing item.",
    "Share information about your property availability",
    "Description",
    "Generate",
    "Choose how many words you want to generate",
    "Number Of Words ",
    "Type your package title",
    "e.g. Athens : A Historical Start",
    "AI assistant",
    "Enhance your tour Products with AI! 🎯. Let us auto-generate rich, detailed descriptions to attract more bookings. Want to try it now?",
    "Write with ",
    "Share what makes your place special.",
    "Create your description",
    "Description",
    "Add new discount",
    "Description",
    "Title",
    "Offer % of discount for stays of 28 nights or more",
    "Monthly discount",
    "Offer % of discount for stays of 7 nights or more",
    "Weekly discount",
    "Offer % off your first 3 bookings",
    "New listing promotion",
    "Help your place stand out to get booked faster and earn your first reviews.",
    "Add discounts",
    "Finally, you'll choose booking settings, set up pricing, and publish your listing.",
    "Finish up and publish",
    "Phase 3",
    "Guests",
    "Bedrooms",
    "Bathrooms",
    "Beds",
    "This is core information for your listing item",
    "Share information about your listings",
    "'This is core information for your listing item",
    "Get started",
    "Loading...",
    "Create a new listing",
    "Finish your listing",
    "Welcome back",
    "Get started",
    "Your address is shared with guests when they visit your listings.",
    "Confirm your address",
    "Loading...",
    "Zip Code",
    "-- Choose Destination --",
    "Select Destination",
    "Your address is only shared with guests after they’ve made a reservation.",
    "Where's your place located?",
    "Distance (km)",
    "Place Title",
    "Pick Nearby Places on Map",
    "Property Location",
    "This is optional information for your listing item.",
    "Share information about nearby places",
    "Use AI",
    "Select Thumbnail",
    "Thumbnail Image",
    "Upload Image",
    "or browse for photo",
    "Drag and drop",
    "Generate",
    "Image Type",
    "e.g. Tropical beach at sunset with turquoise water, white sand, palm trees, and happy couple walking.",
    "Describe about your image",
    "Bring your tour packages to life with AI-generated images! 🖼️ Let us create stunning visuals to boost engagement and bookings. Ready to generate your images?",
    " AI assistant",
    "Generate image with ",
    "Enter image title",
    "Image Title",
    "Now, set your base prices",
    "Tip: Set different rates for nightly, weekly, and monthly stays.",
    "Add Refund Rule",
    "Is this property's booking refundable?",
    "Show less",
    "You earn",
    "Guest service fee",
    "Base price (Nightly)",
    "Guest price with taxes",
    "Monthly",
    "Weekly",
    "Nightly",
    "Select Rate Type",
    "Tip: Set different rates for nightly, weekly, and monthly stays.",
    "Now, set your base prices",
    "Refund Message",
    "Days Before Check-in",
    "Be clear about restrictions (smoking, pets, noise). Specify check-in/out times. Mention any guest policies. Highlight safety requirements. Keep rules reasonable and enforceable.",
    "Tips for good house rules",
    "Add Another Rule",
    "Example: No smoking, No parties, Check-in before 10P",
    "House Rules",
    "Does your place have any of these?",
    "Share house rules",
    "Security cameras that monitor indoor spaces are not allowed even if they're turned off. All exterior security cameras must be disclosed.",
    "Important things to know",
    "Add Custom Option",
    "Custom safety item",
    "Weapon(s) on the property",
    "Noise decibel monitor present",
    "Exterior security camera present",
    "Does your place have any of these?",
    "Share safety details",
    "In this step, you’ll add some of the amenities your place offers, plus 5 or more photos. Then, you’ll create a title and description.",
    "Make your place stand out",
    "Phase 2",
    "Which of these best describes your place?",
    "What style of place will guests have?",
    "🚀 Boost Your Property Listings with AI Magic! Struggling to write catchy titles? Let our AI do the work! 🎯We’ll auto-generate rich, eye-catching titles that bring in more bookings — effortlessly. Ready to level up your tour product? 👉 Try it now!",
    "Write some text about your property type",
    "e.g. Kerela house boat package",
    "Choose how many words you want to generate",
    "Number Of Words",
    "What type of place will guests have?",
    "Payout",
    "Select Bank Currency",
    "Automatic Payout",
    "Select Bank",
    "Select Transfer",
    "Select Bank Currency",
    "Amount In Base Currency",
    "Charge Percentage",
    "Request Amount",
    "Payout Method",
    "Automatic Payout",
    "Select Bank Currency",
    "Charge",
    "Total Amount In Base Currency",
    "Payout Method",
    "Paypal Id",
    "Select Recipient",
    "Select Recipient Type",
    "Amount In Base Currency",
    "Charge Percentage",
    "Payout Filter",
    "Created time",
    "Transaction ID",
    "Payout History",
    "Your preferred payout method?",
    "You current balance is: ",
    "Withdraw processing is off today. Please try",
    "Are you sure you want to delete this property?",
    "Delete Property",
    "Edit listing",
    "No listings found.",
    "Seo",
    "Complete listing",
    "Edit listing",
    "Remove listing",
    "Pending",
    "Hard Rejected",
    "Soft Rejected",
    "Hold",
    "Resubmission",
    "In progress",
    "No image available",
    "Location",
    "Listing",
    "Your listing",
    "Save changes",
    "Browse your file here",
    "Meta Image",
    "OG Description",
    "Meta Description",
    "Type and press Enter",
    "Meta Keywords",
    "Meta Title",
    "Page Title",
    "Edit SEO Meta",
    "Seo Update",
    "Taxes",
    "Are you sure you want to remove this tax?",
    "Confirm Deletion",
    "Enable this tax",
    "Edit Tax",
    "Create",
    "Fixed Amount",
    "Percentage",
    "Tax Type",
    "Select Tax Type",
    "Create Tax",
    "Amount",
    "Title",
    "Taxes",
    "Here's your hosting performance overview from ",
    "Welcome back",
    "Cancelled Booking",
    "Completed Booking",
    "Percentage",
    "Refund Booking",
    "Average Rating for all time",
    "Average Rating",
    "from last month",
    "Balance",
    "Host Received",
    "Total Amount",
    "Site Charge",
    "Discount Amount",
    "Amount without Discount",
    "Guests",
    "Check-out",
    "Booking ID",
    "Booking Info",
    "Message",
    "Details",
    "Upcoming",
    "Upcoming Check-Ins",
    "View All",
    "Date",
    "Booking Chart",
    "Transactions",
    "Earnings",
    "Earnings History",
    "Total",
    "Host received",
    "Vibestay service fee",
    "Discounts",
    "Gross earnings",
    "This Year Summery",
    "Earnings",
    "Host Received",
    "Total Amount",
    "Site Charge",
    "Discount Amount",
    "Amount without Discount",
    "Maintenance",
    "No reviews available for this host",
    "No properties available for this host",
    "View Rooms",
    "Additional charges like service fees, local taxes, or cleaning fees may apply.",
    "Excl. taxes",
    "& fees",
    "See Available dates",
    "Type here to search",
    "Email: ",
    "Contact Information",
    "You are banned from this application. Please contact with system Administrator.",
    "!!!BANNED!!!",
    "Back To Home",
    "No Data Found!",
    "Payment Failed",
    "Sorry",
    "We really appreciate you giving us a moment of your time today but unfortunately the payment was unsuccessful due to",
    "Go Back to Home",
    "All Rights Reserved",
    "Copyright",
    "our administrators are working diligently to set up relevant content for our",
    "audience. We appreciate your patience as we strive to provide valuable information in your preferred language.",
    "Go To Settings",
    "If there is no content available in",
    "Coming Soon Content in",
    "Payment Success",
    "THANK YOU",
    "Thanks a bunch for filling that out. It means a lot to us, just like you do! We really appreciate you giving us a moment of your time today. Thanks for being with us.",
    "We couldn’t find any rentals matching your search.",
    "Please modify your search criteria and try again."
];
